apiVersion: v1
kind: Service
metadata:
  name: air-carrier-nodeport
  labels:
    app: carrier
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31001
  selector:
    app: carrier
     